@startuml

class Person {
}

class Student {

}

Person <|-- Student

class School {
    students: Student[]

    enroll(s: Student)
}

class ElementarySchool
class MiddleSchool
class University

School <|-- ElementarySchool
School <|-- MiddleSchool
School <|-- University

@enduml